name: Build 小明同学 Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32s3
          command: |
            cp sdkconfig.defaults.esp32s3 sdkconfig.defaults
            echo "CONFIG_BOARD_TYPE_WAVESHARE_ESP32_S3_TOUCH_LCD_1_83=y" >> sdkconfig.defaults
            idf.py build

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi-firmware
          path: build/*.bin
